name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
      with:
        bundler-cache: true

    - name: Run tests
      run: bundle exec ruby test_convert_to_json.rb

    - name: Merge PR
      run: gh pr merge --squash "$PR_URL"
      env:
        GH_TOKEN: ${{ github.token }}
        PR_URL: ${{ github.event.pull_request.html_url }}
