name: Update data

on:
  schedule:
    - cron: '0 0 * * SAT'
  workflow_dispatch:

permissions:
  contents: write

env:
  APPLICATION_ID: ${{ secrets.APPLICATION_ID }}

jobs:
  update-data:
    name: Update data
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
      with:
        bundler-cache: true

    - name: Run data update script
      run: ./update-data.sh

    - name: Run tests
      run: bundle exec ruby test_convert_to_json.rb

    - name: Commit and push
      run: |
        if git diff --quiet -- data.json; then
          echo "No changes detected"
          exit 0
        fi

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "Update data.json on $(date +"%Y-%m-%d")"
        git push
